version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 1s
      timeout: 3s
      retries: 30

  order_system:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: order_system
    restart: always
    environment:
      # MySQL
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: orders
      DB_MIGRATION_FOLDER: migrations
      # Webserver
      WEB_SERVER_PORT: 8000
      # gRPC
      GRPC_SERVER_PORT: 50051
      # GraphQL
      GRAPHQL_SERVER_PORT: 8080
      # Rabbit
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    ports:
      - 8000:8000
      - 50051:50051
      - 8080:8080
    depends_on:
      rabbitmq:
        condition: service_healthy
